### ISSUE TITLE
Bing DEM Height Clarification

### ISSUE THREAD

**Issue by jgr007** [seanisom/flightsimlib#3]
I'm not sure this is the right place to ask this, but I'm confused on the Bing Height.  Here is the sample code and explanation in the doc:

Then you do a signed 16 bit addition of the average height with the value, and then subtract the minimum lookup index to get the table lookup value.

Where dx, dy are your width and height indices respectively, and data is your decompressed jxr:

const auto value = *(int16_t*)(data + 2 * (dx * width + dy));
const auto lookup = (int16_t)temp_data + (int16_t)avg_height;
const auto height = scaleMeters[val - lookup];

I'm confused about what temp_data is and also the difference, if any, between value in line 1 and and val in line 3.

Thanks much for the code and explanation about the format.  This is the only detail I can find about those tiles.

**Comment by seanisom** [comment]
Hi,

Thanks for reaching out. You are indeed correct in that the code is unclear and I missed some renamed variables. I will update the documentation (and hopefully soon port a working implementation to this repo), and here's what it should be:

```
// the first cast is necessary as data is a uint8_t []
const auto value = (int16_t)(data + 2 * (dx * width + dy));
// This middle cast is in the code but doesn't seem necessary
const auto lookup = (int16_t)value + (int16_t)avg_height;
// This decoded lookup value is normalized then the index into the height array
const auto height = scaleMeters[lookup - scaleMinIndex];
```

Basically the jxr value is added to the average, normalized, then looked up in the table. 

Hopefully that is clearer - let me know if that makes sense.

**Comment by jgr007** [comment]
Great...that makes sense.  Thanks much for the clarification...I appreciate the help!
